### ISSUE TITLE
Optimal setting to use with Wordpress + NextCloud?

### ISSUE THREAD

**Issue by mjackstone6** [evertramos/docker-nextcloud-letsencrypt#5]
First of all, thank you for this repository and also the WordPress repository.
It has saved me a lot of time setting up my new VPS and a WordPress docker instance. 

I am now looking to include your NextCloud repository under the same domain (but under the cloud subdomain like your sample suggests) and wondering what is the optimal way to set this up on the same instance? My concern is that we create a database for the WordPress instance and the NextCloud instance  also seems to create a database which will create unnecessary overhead.

What is the best way to get something like above setup?

**Comment by evertramos** [comment]
Hello @mjackstone6,

Thanks for your kind words and using out script!

I have transfered this issue to nextcloud once I understand is not a proxy issue, but you want to use one instance of MYSQL to run both databases, wordpress and nextcloud, is that correct?

First of all everything I will comment below is in most part my opinion and my way of thinking on how to operate services, so, please do not take it wrong... I might suggest but anyone does whatever think is right, and I am not saying whoever does other way is right or wrong, ok? 

When running docker we have the idea of abstracting services, which means we would run one service at a time, using the host processing (limiting or not) power, memory etc... but in that scenario we might incur in some hardware limitation... I myself has ran into some issued like that. What have a done? 

Well, my own servers runs different clients environments, so, each one has a specific peculiarity on the way they process data and communication... In two of my servers which I run wordpress sites for the clients I use one database for each service, limiting and charging for usage on storage and processing. 

In that scenario I believe the best way would be to keep it separately for each service, once I use my wordpress compose file which put up and down services together, but joining databases would need only one small script to create database in the mysql (master) instance and connect it to the customer network everytime we start a new customer and backup and remove database everytime a customer change servers or cancels the service (does not really happen a lot). 

So, in this point of view I think this might be an option to have one instance of mysql, but I am pretty sure depending on the number of containers running mysql, it would be useless, the process and memory you use from the server would not be that much and running only a couple (4 or 5) mysql container instances... but I have never done a benchmark on that to see if this really save server resources. 

One of my clients which holds the operation for himself and I only do some support on that uses one instance to server all customers databases, which in that case is quiet a lot, making in easier to backup the whole service instead of having specific services being saved every minute.

So, where is pros and cons on both sides, and I strongly recommend doing some tests on both before choose a path to walk it through.

Also, when using a centralized database, I would remove all connections from the docker-compose file and only add a small script to create database and call the compose file when starting a new service.

I hope you find something helpful in my comments.

Cheers!

**Comment by mjackstone6** [comment]
Hey @evertramos thanks for the helpful hints. At this stage I am testing both having one centralized database and also testing WordPress / NextCloud both having individual databases. So far it they seem to both work under the same resource load but I found it easier to configure a single database. 

I am still messing around with optimal settings but I will update this issue later with my configuration for people that may attempt something similar to me.

**Comment by evertramos** [comment]
Nice! Thanks!

We will keep it open until you come back with some hints on that.

About optimize docker containers, only thing that comes on my mind now is to dedicate some memory to the container which will guarantee it's response when required.

And just some basic for the record only, you for sure is already doing it, create users for each services and databases. restricting access to what is necessary.

There is a couple tuning up settings which might be used but very specific for each dba's... you might can [qwant](https://www.qwant.com/) it and find a lot of good stuff.

Hardware... I had a lot of improvement using ssd for the database partitions, if you have an specific drive for the db files even better.

Well I think this is what I can come up with so far... but we can keep increment it if anything else come up.

**Comment by mjackstone6** [comment]
Hey, appreciate your detailed response.

I've spent the last couple months playing around with the settings and having a MySQL db for each application was indeed the right way to go.

Now I've run into another problem that I hope you could help me troubleshoot.
I currently have NextCloud, WordPress and the LetsEncrypt containers (all the same settings as the docker-compose and .env files) but I've recently run into a small issue regarding WordPress not being able to update as seen by this [issue](https://github.com/evertramos/docker-wordpress-letsencrypt/issues/27). It was fixed by running the commands:
`$ chgrp -R www-data /path/to/your/files/wp-content
$ chmod 775 -R /path/to/your/files/wp-content`

Then I noticed that I was unable to upload any files greater than 1mb to NextCloud. For some reason, the logs aren't being generated from within the container so its kind of hard to debug the issues. So far I've tried changing permissions in the data folder, setting client_max_body_size as indicated by this [issue](https://github.com/nextcloud/docker/issues/404). 

Do you have any idea how this could be fixed?

**Comment by evertramos** [comment]
This is related to the upload limit set in the php.ini in the nextcloud settings and in the webproxy:

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/master/conf.d/uploadsize.conf

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/5961d414c9c2cfbbdb702a37f3db8ea7a6a8fa9b/.env.sample#L63

**Comment by evertramos** [comment]
We will close this issue than and if you need we can keep this discussion on, ok? Thanks!
